version: '3'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=bomdiaimagens
      - POSTGRESQL_PASSWORD=12345678
      - POSTGRESQL_DATABASE=bomdiaimagens
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    ports:
      - '5432:5432'

volumes:
  postgresql_data:
    driver: local